version: "3"
services:
  mongo:
    image: "nosql-mongodb"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mongodb-container
    restart: always
    ports:
        - 27017:27017
    volumes:
        - mongodb:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express-container
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
    depends_on:
      - mongo


volumes:
  mongodb: